//! Integration tests for `rec export` command (EXIM-01,02,06,08,09,10,11,12).

mod common;

use std::collections::HashMap;
use std::path::PathBuf;

use common::TestEnv;
use rec::export::parameterize::{Parameter, detect_all_parameters};
use rec::models::{Command, Session, SessionFooter, SessionHeader, SessionStatus};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Helper: create a session with specific env vars and hostname
// ---------------------------------------------------------------------------

#[allow(clippy::cast_possible_truncation, clippy::cast_precision_loss)]
fn session_with_env(
    name: &str,
    env: HashMap<String, String>,
    hostname: &str,
    commands: &[(&str, &str)],
) -> Session {
    let cmds: Vec<Command> = commands
        .iter()
        .enumerate()
        .map(|(i, (cmd, cwd))| Command {
            index: i as u32,
            command: cmd.to_string(),
            cwd: PathBuf::from(cwd),
            started_at: 1_700_000_000.0 + i as f64,
            ended_at: Some(1_700_000_001.0 + i as f64),
            exit_code: Some(0),
            duration_ms: Some(1000),
        })
        .collect();

    let count = cmds.len() as u32;
    Session {
        header: SessionHeader {
            version: 2,
            id: Uuid::new_v4(),
            name: name.to_string(),
            shell: "bash".to_string(),
            os: "linux".to_string(),
            hostname: hostname.to_string(),
            env,
            tags: Vec::new(),
            recovered: None,
            started_at: 1_700_000_000.0,
        },
        commands: cmds,
        footer: Some(SessionFooter {
            ended_at: 1_700_000_060.0,
            command_count: count,
            status: SessionStatus::Completed,
        }),
    }
}

// ---------------------------------------------------------------------------
// EXIM-01: export_bash produces valid bash script
// ---------------------------------------------------------------------------

#[test]
fn test_export_bash_produces_valid_script() {
    let env = TestEnv::new();
    let session = env.create_session_with_commands("bash-export", &["echo hello", "ls -la"]);

    let result = rec::export::export_bash(&session, None);

    assert!(result.starts_with("#!/bin/bash\n"), "must have shebang");
    assert!(
        result.contains("set -euo pipefail"),
        "must have strict mode"
    );
    assert!(result.contains("echo hello"), "must contain commands");
    assert!(result.contains("ls -la"), "must contain all commands");
    assert!(
        result.contains("# Generated by rec"),
        "must have generator comment"
    );
}

// ---------------------------------------------------------------------------
// EXIM-02: export_makefile produces valid Makefile
// ---------------------------------------------------------------------------

#[test]
fn test_export_makefile_produces_valid_makefile() {
    let env = TestEnv::new();
    let session = env.create_session_with_commands("make-export", &["echo hello", "make build"]);

    let result = rec::export::export_makefile(&session, None);

    assert!(result.contains(".PHONY:"), "must have .PHONY targets");
    // Verify tab-indented commands
    assert!(
        result.lines().any(|l| l.starts_with('\t')),
        "must have tab-indented recipe lines"
    );
    assert!(result.contains("step-1:"), "must have step targets");
    assert!(result.contains("step-2:"), "must have all step targets");
    assert!(
        result.contains("# Generated by rec"),
        "must have generator comment"
    );
}

// ---------------------------------------------------------------------------
// EXIM-06: export_markdown produces markdown with code blocks
// ---------------------------------------------------------------------------

#[test]
fn test_export_markdown_produces_markdown() {
    let env = TestEnv::new();
    let session = env.create_session_with_commands("md-export", &["echo hello", "pwd"]);

    let result = rec::export::export_markdown(&session, None);

    assert!(
        result.contains("# Session: md-export"),
        "must have title heading"
    );
    assert!(result.contains("```bash"), "must have fenced code blocks");
    assert!(result.contains("```\n"), "must close code blocks");
    assert!(result.contains("echo hello"), "must contain commands");
    assert!(
        result.contains("*Generated by rec*"),
        "must have generator note"
    );
}

// ---------------------------------------------------------------------------
// EXIM-08: export --output writes to file
//
// The binary does not support env-var path overrides, so we test the
// --output flag acceptance via CLI (nonexistent session reaches session
// lookup, proving the flag is parsed) and verify file-writing logic at
// the library level.
// ---------------------------------------------------------------------------

#[test]
fn test_export_output_flag_accepted_by_cli() {
    // Verify --output flag is parsed: error should be "not found" (session
    // lookup), not a flag parse error.
    #[allow(deprecated)]
    let mut cmd = assert_cmd::Command::cargo_bin("rec").expect("binary 'rec' should be findable");

    cmd.args([
        "export",
        "nonexistent-output-test-xyz",
        "--format",
        "bash",
        "--output",
        "/tmp/rec-test-export-output.sh",
    ]);
    cmd.assert().failure().code(1);
}

#[test]
fn test_export_output_writes_file_library() {
    let env = TestEnv::new();
    let session = env.create_session_with_commands("file-export", &["echo hello"]);

    let content = rec::export::export_bash(&session, None);
    let output_path = env.paths.data_dir.join("exported.sh");
    std::fs::write(&output_path, &content).expect("write should succeed");

    let read_back = std::fs::read_to_string(&output_path).expect("file should exist");
    assert!(
        read_back.starts_with("#!/bin/bash\n"),
        "file must have shebang"
    );
    assert!(
        read_back.contains("set -euo pipefail"),
        "file must have strict mode"
    );
}

// ---------------------------------------------------------------------------
// EXIM-09: detect_all_parameters detects env values
// ---------------------------------------------------------------------------

#[test]
fn test_parameterize_detects_env_values() {
    let mut env_map = HashMap::new();
    env_map.insert("HOME".to_string(), "/home/alice".to_string());
    env_map.insert("USER".to_string(), "alice".to_string());

    let session = session_with_env(
        "param-detect",
        env_map,
        "workstation",
        &[
            ("ls /home/alice/docs", "/home/alice"),
            ("whoami | grep alice", "/tmp"),
            ("ssh workstation", "/tmp"),
        ],
    );

    let params = detect_all_parameters(&session);

    let names: Vec<&str> = params.iter().map(|p| p.name.as_str()).collect();
    assert!(names.contains(&"HOME_DIR"), "must detect HOME_DIR");
    assert!(names.contains(&"USERNAME"), "must detect USERNAME");
    assert!(names.contains(&"HOSTNAME"), "must detect HOSTNAME");
    assert!(
        params.iter().all(|p| p.auto_detected),
        "all should be auto-detected"
    );
}

// ---------------------------------------------------------------------------
// EXIM-10: parameter value override replaces original values
// ---------------------------------------------------------------------------

#[test]
fn test_param_value_override_replaces_in_output() {
    let mut env_map = HashMap::new();
    env_map.insert("HOME".to_string(), "/home/alice".to_string());

    let session = session_with_env(
        "param-override",
        env_map,
        "unknown",
        &[("cat /home/alice/file.txt", "/home/alice")],
    );

    let params = vec![Parameter {
        name: "HOME_DIR".to_string(),
        original: "/home/alice".to_string(),
        value: Some("/opt/deploy".to_string()),
        auto_detected: true,
    }];

    let result = rec::export::export_bash(&session, Some(&params));

    // Variable declaration should use override value
    assert!(
        result.contains("HOME_DIR=\"/opt/deploy\""),
        "declaration must use override value"
    );
    // Commands should reference the variable, not original value
    assert!(
        result.contains("$HOME_DIR"),
        "commands must use variable reference"
    );
    assert!(
        !result.contains("/home/alice"),
        "original value must not appear in commands"
    );
}

// ---------------------------------------------------------------------------
// EXIM-11: invalid format via CLI shows possible values and exits nonzero
// ---------------------------------------------------------------------------

#[test]
fn test_invalid_format_shows_possible_values() {
    #[allow(deprecated)]
    let mut cmd = assert_cmd::Command::cargo_bin("rec").expect("binary 'rec' should be findable");

    cmd.args(["export", "any-session", "--format", "invalidformat"]);
    // clap exits with code 2 for invalid enum values
    cmd.assert().failure().code(2);
}

// ---------------------------------------------------------------------------
// EXIM-12: nonexistent session exits 1
// ---------------------------------------------------------------------------

#[test]
fn test_nonexistent_session_exits_1() {
    #[allow(deprecated)]
    let mut cmd = assert_cmd::Command::cargo_bin("rec").expect("binary 'rec' should be findable");

    cmd.args([
        "export",
        "nonexistent-session-xyz-99999",
        "--format",
        "bash",
    ]);
    cmd.assert().failure().code(1);
}
